enable-plugin: false
settings:
  host: 'http(s)://example.com'
  api-key: ' '
  server-id: 0
ranks-order:
    - 1
    - 2
messages:
  permission: '&cSorry, you cannot use this.'
  usage: '&cUsage: /litenameless &e<reload>&c.'
  reload: '&aReloaded LiteNameless!'
do-not-touch-version: 1