name: ${plugin.name}
main: space.arim.nameless.spigot.LiteNamelessSpigot
version: ${plugin.version}
author: ${plugin.author}
website: ${plugin.url}
description: ${plugin.description}
depend: [ArimAPI]

commands:
  litenameless:
    description: Everything related to LiteNameless
    usage: /litenameless <arguments>